# Workflow name:
name: Vercel Preview Deployment

# Workflow environment variables:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Workflow triggers:
on:
  # Trigger the workflow on push events (excluding the main branch):
  push:
    branches-ignore:
      - main

# Workflow jobs:
jobs:
  # Define a job to create a Vercel preview deployment:
  Deploy-Preview:
    # Define display name:
    name: 'Deploy Preview'

    # Define the type of machine to run the job on:
    runs-on: ubuntu-latest

    # Define the steps to run the job:
    steps:
      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Install the Vercel CLI:
      - name: 'Install Vercel CLI'
        run: npm install --global vercel@latest

      # Pull the Vercel environment information:
      - name: 'Pull Vercel Environment Information'
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      # Build the project artifacts:
      - name: 'Build Project Artifacts'
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy the project artifacts to Vercel:
      - name: 'Deploy Project Artifacts to Vercel'
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
