# Workflow name:
name: Vercel Production Deployment

# Workflow environment variables:
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

# Workflow triggers:
on:
  # Trigger the workflow on push events to the main branch:
  push:
    branches:
      - main

# Workflow jobs:
jobs:

  # Define a job to deploy to the production environment...
  Deploy-Production:
    # Define display name:
    name: 'Deploy to Production'

    # Define the type of machine to run the job on:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Install the Vercel CLI:
      - name: 'Install Vercel CLI'
        run: npm install --global vercel@latest

      # Pull the Vercel environment information:
      - name: 'Pull Vercel Environment Information'
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # Build and deploy the project artifacts:
      - name: 'Build Project Artifacts'
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # Deploy the project artifacts to Vercel:
      - name: 'Deploy Project Artifacts to Vercel'
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
