# Workflow name:
name: Send digest email

# Workflow triggers:
on:
  pull_request:
    types: [closed]
    branches: [main]

# Workflow jobs:
jobs:
  # Define job to send daily digest email:
  email:
    # Define display name:
    name: 'Send daily digest email'

    # Only run for merged pull requests and skip if "skip-email" label is present:
    if: > 
      github.event.pull_request.merged == true && 
      !contains(github.event.pull_request.labels.*.name, 'skip-email')

    # Define the type of virtual host machine:
    runs-on: 'ubuntu-latest'

    # Define the sequence of job steps...
    steps:
      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      # Install Node.js:
      - name: 'Install Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 20
        timeout-minutes: 5

      # Install dependencies:
      - name: 'Install dependencies'
        run: 'npm install'
        timeout-minutes: 5

      # Send email:
      - name: 'Send email'
        run: 'node scripts/send_digest_email.js'
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
          MAILCHIMP_API_SERVER: ${{ secrets.MAILCHIMP_API_SERVER }}
        timeout-minutes: 15
