# Workflow name:
name: Update index.mdx

on:
  # Merged pull requests:
  pull_request:
    types: [closed]
    branches: [main]

# Workflow jobs:
jobs:
  # Define job to update index.mdx:
  update:
    # Define display name:
    name: 'Update index.mdx'

    # Define the type of virtual host machine:
    runs-on: 'ubuntu-latest'

    # Define the sequence of job steps...
    steps:
      # Checkout the repository:
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Install Node.js:
      - name: 'Install Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: 16
        timeout-minutes: 5

      # Install dependencies:
      - name: 'Install dependencies'
        run: 'npm install'
        timeout-minutes: 5

      # Update index.mdx:
      - name: 'Update index.mdx'
        run: 'node scripts/update_index_mdx.js'
        timeout-minutes: 15

      # Commit changes:
      - name: 'Commit changes'
        run: |
          git config --local user.email 'pburckhardt@outlook.com'
          git config --local user.name 'Planeshifter'
          git add www/src/pages/index.mdx
          git commit -m 'Update index.mdx'
        timeout-minutes: 5

      # Push changes:
      - name: 'Push changes'
        run: |
          SLUG=${{ github.repository }}
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$SLUG.git"
